/**
 * Regenerated by `npm run scrape`.
 *
 * The scraper writes ./cards.json and rewrites this file to import it. Kept as
 * a real module rather than a directory glob so it typechecks and works
 * identically under Turbopack and Webpack.
 */
export const SCRAPED_CARDS: unknown[] = [];
